// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pjatk_apbd_Kolokwium2A.Data;

#nullable disable

namespace pjatk_apbd_Kolokwium2A.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250608094146_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.AvailableProgram", b =>
                {
                    b.Property<int>("AvailableProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailableProgramId"));

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<int>("ProgramId")
                        .HasColumnType("int");

                    b.Property<int>("WashingMachineId")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("WashingMachineId");

                    b.ToTable("AvailableProgram");

                    b.HasData(
                        new
                        {
                            AvailableProgramId = 1,
                            Price = 12m,
                            ProgramId = 1,
                            WashingMachineId = 1
                        },
                        new
                        {
                            AvailableProgramId = 2,
                            Price = 10m,
                            ProgramId = 2,
                            WashingMachineId = 1
                        },
                        new
                        {
                            AvailableProgramId = 3,
                            Price = 6m,
                            ProgramId = 3,
                            WashingMachineId = 2
                        });
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Jan",
                            LastName = "Motyl"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Marianna",
                            LastName = "Motyl"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Kamil",
                            LastName = "Woch",
                            PhoneNumber = "123123123"
                        });
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.Program", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TemperatureCelsius")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.ToTable("Program");

                    b.HasData(
                        new
                        {
                            ProgramId = 1,
                            DurationMinutes = 30,
                            Name = "Szybkie",
                            TemperatureCelsius = 30
                        },
                        new
                        {
                            ProgramId = 2,
                            DurationMinutes = 15,
                            Name = "Wirowanie",
                            TemperatureCelsius = 30
                        },
                        new
                        {
                            ProgramId = 3,
                            DurationMinutes = 180,
                            Name = "Eco",
                            TemperatureCelsius = 40
                        });
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.PurchaseHistory", b =>
                {
                    b.Property<int>("AvailableProgramId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("AvailableProgramId", "CustomerId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseHistory");

                    b.HasData(
                        new
                        {
                            AvailableProgramId = 1,
                            CustomerId = 1,
                            PurchaseDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            AvailableProgramId = 2,
                            CustomerId = 3,
                            PurchaseDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        },
                        new
                        {
                            AvailableProgramId = 3,
                            CustomerId = 2,
                            PurchaseDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Rating = 5
                        });
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.WashingMachine", b =>
                {
                    b.Property<int>("WashingMachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WashingMachineId"));

                    b.Property<decimal>("MaxWeight")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WashingMachineId");

                    b.ToTable("WashingMachine");

                    b.HasData(
                        new
                        {
                            WashingMachineId = 1,
                            MaxWeight = 15m,
                            SerialNumber = "1234567890"
                        },
                        new
                        {
                            WashingMachineId = 2,
                            MaxWeight = 12m,
                            SerialNumber = "1234567891"
                        },
                        new
                        {
                            WashingMachineId = 3,
                            MaxWeight = 15m,
                            SerialNumber = "1234567895"
                        });
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.AvailableProgram", b =>
                {
                    b.HasOne("pjatk_apbd_Kolokwium2A.Models.Program", "Program")
                        .WithMany("AvaliblePrograms")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pjatk_apbd_Kolokwium2A.Models.WashingMachine", "WashingMachine")
                        .WithMany("AvaliblePrograms")
                        .HasForeignKey("WashingMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Program");

                    b.Navigation("WashingMachine");
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.PurchaseHistory", b =>
                {
                    b.HasOne("pjatk_apbd_Kolokwium2A.Models.AvailableProgram", "AvailableProgram")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("AvailableProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pjatk_apbd_Kolokwium2A.Models.Customer", "Customer")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailableProgram");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.AvailableProgram", b =>
                {
                    b.Navigation("PurchaseHistories");
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.Customer", b =>
                {
                    b.Navigation("PurchaseHistories");
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.Program", b =>
                {
                    b.Navigation("AvaliblePrograms");
                });

            modelBuilder.Entity("pjatk_apbd_Kolokwium2A.Models.WashingMachine", b =>
                {
                    b.Navigation("AvaliblePrograms");
                });
#pragma warning restore 612, 618
        }
    }
}
